// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/99designs/gqlgen/graphql"
)

type Achievement struct {
	Title       string          `json:"title"`
	Description string          `json:"description"`
	IconType    AchievementIcon `json:"iconType"`
}

type Application struct {
	ID             string  `json:"id"`
	OpportunityID  *string `json:"opportunityId,omitempty"`
	EventID        string  `json:"eventId"`
	ApplierID      string  `json:"applierId"`
	ApplicantName  *string `json:"applicantName,omitempty"`
	ApplicantEmail *string `json:"applicantEmail,omitempty"`
	ApplicantPhone *string `json:"applicantPhone,omitempty"`
	Description    *string `json:"description,omitempty"`
	ResumeURL      *string `json:"resumeUrl,omitempty"`
	Status         string  `json:"status"`
	CreatedAt      string  `json:"createdAt"`
}

type Author struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Cart struct {
	Lines []*CartLine `json:"lines"`
	Total float64     `json:"total"`
}

type CartLine struct {
	Listing  *Listing       `json:"listing"`
	Quantity int32          `json:"quantity"`
	Issue    *CartLineIssue `json:"issue,omitempty"`
}

type Category struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Comment struct {
	ID        string `json:"id"`
	PostID    string `json:"postId"`
	UserID    string `json:"userId"`
	UserName  string `json:"userName"`
	Content   string `json:"content"`
	CreatedAt string `json:"createdAt"`
}

type CreateApplicationInput struct {
	OpportunityID  *string `json:"opportunityId,omitempty"`
	EventID        string  `json:"eventId"`
	ApplicantName  *string `json:"applicantName,omitempty"`
	ApplicantEmail *string `json:"applicantEmail,omitempty"`
	ApplicantPhone *string `json:"applicantPhone,omitempty"`
	Description    *string `json:"description,omitempty"`
	ResumeURL      *string `json:"resumeUrl,omitempty"`
}

type CreateCommentInput struct {
	PostID  string `json:"postId"`
	Content string `json:"content"`
}

type CreateEventInput struct {
	Name      string `json:"name"`
	StartDate string `json:"startDate"`
	Duration  string `json:"duration"`
}

type CreateListingInput struct {
	Title       string   `json:"title"`
	Description *string  `json:"description,omitempty"`
	Price       float64  `json:"price"`
	Stock       int32    `json:"stock"`
	ImageUrls   []string `json:"imageUrls"`
	CategoryID  string   `json:"categoryId"`
}

type CreateOpportunityInput struct {
	EventID        string   `json:"eventId"`
	Title          string   `json:"title"`
	Description    *string  `json:"description,omitempty"`
	Categories     []string `json:"categories,omitempty"`
	Location       *string  `json:"location,omitempty"`
	StartDate      *string  `json:"startDate,omitempty"`
	EndDate        *string  `json:"endDate,omitempty"`
	TotalPositions *int32   `json:"totalPositions,omitempty"`
	Status         *string  `json:"status,omitempty"`
}

type CreatePostInput struct {
	Content    string            `json:"content"`
	Media      []*graphql.Upload `json:"media,omitempty"`
	CategoryID *string           `json:"categoryId,omitempty"`
}

type Event struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	StartDate string  `json:"startDate"`
	Duration  string  `json:"duration"`
	HostID    *string `json:"hostId,omitempty"`
	HostName  *string `json:"hostName,omitempty"`
	CreatedAt string  `json:"createdAt"`
}

type Listing struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Price       float64   `json:"price"`
	Currency    string    `json:"currency"`
	Stock       int32     `json:"stock"`
	ImageUrls   []string  `json:"imageUrls"`
	Category    *Category `json:"category"`
	Seller      *Seller   `json:"seller"`
	CreatedAt   string    `json:"createdAt"`
	Archived    bool      `json:"archived"`
}

type ListingFilter struct {
	Query       *string  `json:"query,omitempty"`
	CategoryID  *string  `json:"categoryId,omitempty"`
	MinPrice    *float64 `json:"minPrice,omitempty"`
	MaxPrice    *float64 `json:"maxPrice,omitempty"`
	InStockOnly *bool    `json:"inStockOnly,omitempty"`
}

type Mutation struct {
}

type OnboardingInput struct {
	Name           string   `json:"name"`
	Role           string   `json:"role"`
	Location       string   `json:"location"`
	Labels         []string `json:"labels,omitempty"`
	Bio            *string  `json:"bio,omitempty"`
	ProfilePicture *string  `json:"profilePicture,omitempty"`
}

type Opportunity struct {
	ID                string   `json:"id"`
	EventID           string   `json:"eventId"`
	Title             string   `json:"title"`
	Description       *string  `json:"description,omitempty"`
	Categories        []string `json:"categories"`
	Location          *string  `json:"location,omitempty"`
	StartDate         *string  `json:"startDate,omitempty"`
	EndDate           *string  `json:"endDate,omitempty"`
	TotalPositions    int32    `json:"totalPositions"`
	OpenSlots         int32    `json:"openSlots"`
	ApplicationsCount int32    `json:"applicationsCount"`
	Status            string   `json:"status"`
	CreatedAt         string   `json:"createdAt"`
}

type Order struct {
	ID              string           `json:"id"`
	Items           []*OrderItem     `json:"items"`
	ShippingAddress *ShippingAddress `json:"shippingAddress"`
	Total           float64          `json:"total"`
	State           OrderState       `json:"state"`
	CreatedAt       string           `json:"createdAt"`
}

type OrderItem struct {
	ID        string           `json:"id"`
	ListingID string           `json:"listingId"`
	Title     string           `json:"title"`
	Price     float64          `json:"price"`
	Quantity  int32            `json:"quantity"`
	Status    FulfilmentStatus `json:"status"`
}

type Post struct {
	ID           string       `json:"id"`
	UserID       string       `json:"userId"`
	UserName     string       `json:"userName"`
	Content      string       `json:"content"`
	Media        []*PostMedia `json:"media"`
	CategoryID   *string      `json:"categoryId,omitempty"`
	CategoryName *string      `json:"categoryName,omitempty"`
	LikeCount    int32        `json:"likeCount"`
	CommentCount int32        `json:"commentCount"`
	IsLikedByMe  bool         `json:"isLikedByMe"`
	CreatedAt    string       `json:"createdAt"`
}

type PostMedia struct {
	ID        string `json:"id"`
	PostID    string `json:"postId"`
	URL       string `json:"url"`
	MediaType string `json:"mediaType"`
	SortOrder int32  `json:"sortOrder"`
	CreatedAt string `json:"createdAt"`
}

type Profile struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Username       string         `json:"username"`
	Location       string         `json:"location"`
	Bio            string         `json:"bio"`
	AvatarURL      *string        `json:"avatarUrl,omitempty"`
	Email          string         `json:"email"`
	Followers      int32          `json:"followers"`
	Following      int32          `json:"following"`
	ArtworksCount  int32          `json:"artworksCount"`
	TotalLikes     int32          `json:"totalLikes"`
	Skills         []string       `json:"skills"`
	ArtworksImages []string       `json:"artworksImages"`
	Achievements   []*Achievement `json:"achievements"`
	RecentPosts    []*ProfilePost `json:"recentPosts"`
}

type ProfilePost struct {
	ID           string  `json:"id"`
	Content      string  `json:"content"`
	MediaType    *string `json:"mediaType,omitempty"`
	MediaURI     *string `json:"mediaUri,omitempty"`
	LikeCount    int32   `json:"likeCount"`
	CommentCount int32   `json:"commentCount"`
	CreatedAt    string  `json:"createdAt"`
}

type Query struct {
}

type Seller struct {
	ID             string  `json:"id"`
	Name           string  `json:"name"`
	Location       *string `json:"location,omitempty"`
	ProfilePicture *string `json:"profilePicture,omitempty"`
}

type SellerOrderItem struct {
	ID              string           `json:"id"`
	OrderID         string           `json:"orderId"`
	ListingID       string           `json:"listingId"`
	Title           string           `json:"title"`
	Price           float64          `json:"price"`
	Quantity        int32            `json:"quantity"`
	Status          FulfilmentStatus `json:"status"`
	ShippingAddress *ShippingAddress `json:"shippingAddress"`
	CreatedAt       string           `json:"createdAt"`
}

type ShippingAddress struct {
	Name       string `json:"name"`
	Phone      string `json:"phone"`
	Line1      string `json:"line1"`
	Line2      string `json:"line2"`
	City       string `json:"city"`
	State      string `json:"state"`
	PostalCode string `json:"postalCode"`
	Country    string `json:"country"`
}

type ShippingAddressInput struct {
	Name       string  `json:"name"`
	Phone      string  `json:"phone"`
	Line1      string  `json:"line1"`
	Line2      *string `json:"line2,omitempty"`
	City       string  `json:"city"`
	State      string  `json:"state"`
	PostalCode string  `json:"postalCode"`
	Country    string  `json:"country"`
}

type UpdateCommentInput struct {
	Content string `json:"content"`
}

type UpdateEventInput struct {
	Name      *string `json:"name,omitempty"`
	StartDate *string `json:"startDate,omitempty"`
	Duration  *string `json:"duration,omitempty"`
}

type UpdateListingInput struct {
	Title       *string  `json:"title,omitempty"`
	Description *string  `json:"description,omitempty"`
	Price       *float64 `json:"price,omitempty"`
	Stock       *int32   `json:"stock,omitempty"`
	ImageUrls   []string `json:"imageUrls,omitempty"`
	CategoryID  *string  `json:"categoryId,omitempty"`
}

type UpdateOpportunityInput struct {
	Title          *string  `json:"title,omitempty"`
	Description    *string  `json:"description,omitempty"`
	Categories     []string `json:"categories,omitempty"`
	Location       *string  `json:"location,omitempty"`
	StartDate      *string  `json:"startDate,omitempty"`
	EndDate        *string  `json:"endDate,omitempty"`
	TotalPositions *int32   `json:"totalPositions,omitempty"`
	Status         *string  `json:"status,omitempty"`
}

type UpdatePostInput struct {
	Content    *string `json:"content,omitempty"`
	CategoryID *string `json:"categoryId,omitempty"`
}

type AchievementIcon string

const (
	AchievementIconTopCreator AchievementIcon = "TOP_CREATOR"
	AchievementIconFollowers  AchievementIcon = "FOLLOWERS"
	AchievementIconFeatured   AchievementIcon = "FEATURED"
)

var AllAchievementIcon = []AchievementIcon{
	AchievementIconTopCreator,
	AchievementIconFollowers,
	AchievementIconFeatured,
}

func (e AchievementIcon) IsValid() bool {
	switch e {
	case AchievementIconTopCreator, AchievementIconFollowers, AchievementIconFeatured:
		return true
	}
	return false
}

func (e AchievementIcon) String() string {
	return string(e)
}

func (e *AchievementIcon) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AchievementIcon(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AchievementIcon", str)
	}
	return nil
}

func (e AchievementIcon) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AchievementIcon) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AchievementIcon) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CartLineIssue string

const (
	CartLineIssueArchived          CartLineIssue = "ARCHIVED"
	CartLineIssueOutOfStock        CartLineIssue = "OUT_OF_STOCK"
	CartLineIssueInsufficientStock CartLineIssue = "INSUFFICIENT_STOCK"
)

var AllCartLineIssue = []CartLineIssue{
	CartLineIssueArchived,
	CartLineIssueOutOfStock,
	CartLineIssueInsufficientStock,
}

func (e CartLineIssue) IsValid() bool {
	switch e {
	case CartLineIssueArchived, CartLineIssueOutOfStock, CartLineIssueInsufficientStock:
		return true
	}
	return false
}

func (e CartLineIssue) String() string {
	return string(e)
}

func (e *CartLineIssue) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CartLineIssue(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CartLineIssue", str)
	}
	return nil
}

func (e CartLineIssue) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CartLineIssue) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CartLineIssue) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FulfilmentStatus string

const (
	FulfilmentStatusPaid      FulfilmentStatus = "PAID"
	FulfilmentStatusShipped   FulfilmentStatus = "SHIPPED"
	FulfilmentStatusDelivered FulfilmentStatus = "DELIVERED"
	FulfilmentStatusCancelled FulfilmentStatus = "CANCELLED"
)

var AllFulfilmentStatus = []FulfilmentStatus{
	FulfilmentStatusPaid,
	FulfilmentStatusShipped,
	FulfilmentStatusDelivered,
	FulfilmentStatusCancelled,
}

func (e FulfilmentStatus) IsValid() bool {
	switch e {
	case FulfilmentStatusPaid, FulfilmentStatusShipped, FulfilmentStatusDelivered, FulfilmentStatusCancelled:
		return true
	}
	return false
}

func (e FulfilmentStatus) String() string {
	return string(e)
}

func (e *FulfilmentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FulfilmentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FulfilmentStatus", str)
	}
	return nil
}

func (e FulfilmentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FulfilmentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FulfilmentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ListingSort string

const (
	ListingSortNewest    ListingSort = "NEWEST"
	ListingSortPriceAsc  ListingSort = "PRICE_ASC"
	ListingSortPriceDesc ListingSort = "PRICE_DESC"
)

var AllListingSort = []ListingSort{
	ListingSortNewest,
	ListingSortPriceAsc,
	ListingSortPriceDesc,
}

func (e ListingSort) IsValid() bool {
	switch e {
	case ListingSortNewest, ListingSortPriceAsc, ListingSortPriceDesc:
		return true
	}
	return false
}

func (e ListingSort) String() string {
	return string(e)
}

func (e *ListingSort) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ListingSort(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ListingSort", str)
	}
	return nil
}

func (e ListingSort) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ListingSort) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ListingSort) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OrderState string

const (
	OrderStatePaid             OrderState = "PAID"
	OrderStatePartiallyShipped OrderState = "PARTIALLY_SHIPPED"
	OrderStateShipped          OrderState = "SHIPPED"
	OrderStateDelivered        OrderState = "DELIVERED"
	OrderStateCancelled        OrderState = "CANCELLED"
)

var AllOrderState = []OrderState{
	OrderStatePaid,
	OrderStatePartiallyShipped,
	OrderStateShipped,
	OrderStateDelivered,
	OrderStateCancelled,
}

func (e OrderState) IsValid() bool {
	switch e {
	case OrderStatePaid, OrderStatePartiallyShipped, OrderStateShipped, OrderStateDelivered, OrderStateCancelled:
		return true
	}
	return false
}

func (e OrderState) String() string {
	return string(e)
}

func (e *OrderState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderState", str)
	}
	return nil
}

func (e OrderState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
