package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"kalasetu/graph/model"
	"kalasetu/models"
	"strconv"
)

// CreateEvent is the resolver for the createEvent field.
func (r *mutationResolver) CreateEvent(ctx context.Context, input model.CreateEventInput) (*model.Event, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	event, err := r.eventService.Create(ctx, userID, models.CreateEventInput{
		Name:      input.Name,
		StartDate: input.StartDate,
		Duration:  input.Duration,
	})
	if err != nil {
		return nil, err
	}
	return toGraphEvent(event), nil
}

// UpdateEvent is the resolver for the updateEvent field.
func (r *mutationResolver) UpdateEvent(ctx context.Context, id string, input model.UpdateEventInput) (*model.Event, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	eventID, err := parseEventID(id)
	if err != nil {
		return nil, err
	}

	event, err := r.eventService.Update(ctx, userID, eventID, models.UpdateEventInput{
		Name:      input.Name,
		StartDate: input.StartDate,
		Duration:  input.Duration,
	})
	if err != nil {
		return nil, err
	}
	return toGraphEvent(event), nil
}

// DeleteEvent is the resolver for the deleteEvent field.
func (r *mutationResolver) DeleteEvent(ctx context.Context, id string) (bool, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return false, err
	}
	eventID, err := parseEventID(id)
	if err != nil {
		return false, err
	}

	if err := r.eventService.Delete(ctx, userID, eventID); err != nil {
		return false, err
	}
	return true, nil
}

// OnboardUser is the resolver for the onboardUser field.
func (r *mutationResolver) OnboardUser(ctx context.Context, input model.OnboardingInput) (bool, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return false, err
	}

	var bio string
	if input.Bio != nil {
		bio = *input.Bio
	}

	var profilePicture string
	if input.ProfilePicture != nil {
		profilePicture = *input.ProfilePicture
	}

	onboardingUser := models.OnboardingUser{
		Name:           input.Name,
		Role:           input.Role,
		Location:       input.Location,
		Labels:         input.Labels,
		Bio:            bio,
		ProfilePicture: profilePicture,
	}

	if err := r.userService.StartOnboarding(ctx, userID, onboardingUser); err != nil {
		return false, err
	}

	return true, nil
}

// SubmitApplication is the resolver for the submitApplication field.
func (r *mutationResolver) SubmitApplication(ctx context.Context, input model.CreateApplicationInput) (*model.Application, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	opportunityID, err := strconv.Atoi(input.OpportunityID)
	if err != nil {
		return nil, err
	}

	serviceInput := models.CreateApplicationInput{
		OpportunityID: opportunityID,
		ResumeURL:     input.ResumeURL,
	}

	application, err := r.applicationService.Create(
		ctx,
		userID,
		serviceInput,
	)

	if err != nil {
		return nil, err
	}

	return toGraphApplication(application), nil
}

// UpdateApplicationStatus is the resolver for the updateApplicationStatus field.
func (r *mutationResolver) UpdateApplicationStatus(ctx context.Context, id string, status string) (bool, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return false, err
	}
	appID, err := strconv.Atoi(id)
	if err != nil {
		return false, fmt.Errorf("invalid application id: %s", id)
	}

	if err := r.applicationService.UpdateStatus(ctx, userID, appID, status); err != nil {
		return false, err
	}
	return true, nil
}

// CreateListing is the resolver for the createListing field.
func (r *mutationResolver) CreateListing(ctx context.Context, input model.CreateListingInput) (*model.Listing, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	categoryID, err := strconv.Atoi(input.CategoryID)
	if err != nil {
		return nil, fmt.Errorf("invalid category id: %s", input.CategoryID)
	}
	var description string
	if input.Description != nil {
		description = *input.Description
	}

	listing, err := r.listingService.Create(ctx, userID, models.CreateListingInput{
		Title:       input.Title,
		Description: description,
		Price:       input.Price,
		Stock:       int(input.Stock),
		ImageURLs:   input.ImageUrls,
		CategoryID:  categoryID,
	})
	if err != nil {
		return nil, err
	}
	return toGraphListing(listing), nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "OK", nil
}

// Events is the resolver for the events field.
func (r *queryResolver) Events(ctx context.Context) ([]*model.Event, error) {
	events, err := r.eventService.List(ctx)
	if err != nil {
		return nil, err
	}
	return toGraphEvents(events), nil
}

// Event is the resolver for the event field.
func (r *queryResolver) Event(ctx context.Context, id string) (*model.Event, error) {
	eventID, err := parseEventID(id)
	if err != nil {
		return nil, err
	}

	event, err := r.eventService.GetByID(ctx, eventID)
	if err != nil {
		return nil, err
	}
	return toGraphEvent(event), nil
}

// Application is the resolver for the application field.
func (r *queryResolver) Application(ctx context.Context, id string) (*model.Application, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	appID, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid application id: %s", id)
	}

	app, err := r.applicationService.FindByID(ctx, userID, appID)
	if err != nil {
		return nil, err
	}
	return toGraphApplication(app), nil
}

// MyApplications is the resolver for the myApplications field.
func (r *queryResolver) MyApplications(ctx context.Context) ([]*model.Application, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	apps, err := r.applicationService.ListByApplier(ctx, userID)
	if err != nil {
		return nil, err
	}
	return toGraphApplications(apps), nil
}

// ApplicationsByOpportunity is the resolver for the applicationsByOpportunity field.
func (r *queryResolver) ApplicationsByOpportunity(ctx context.Context, opportunityID string) ([]*model.Application, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	oppID, err := strconv.Atoi(opportunityID)
	if err != nil {
		return nil, fmt.Errorf("invalid opportunity id: %s", opportunityID)
	}

	apps, err := r.applicationService.ListByOpportunity(ctx, userID, oppID)
	if err != nil {
		return nil, err
	}
	return toGraphApplications(apps), nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*model.Category, error) {
	categories, err := r.listingService.ListCategories(ctx)
	if err != nil {
		return nil, err
	}
	return toGraphCategories(categories), nil
}

// Listing is the resolver for the listing field.
func (r *queryResolver) Listing(ctx context.Context, id string) (*model.Listing, error) {
	listingID, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid listing id: %s", id)
	}
	listing, err := r.listingService.GetByID(ctx, listingID)
	if err != nil {
		return nil, err
	}
	return toGraphListing(listing), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
