package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"kalasetu/graph/model"
	"kalasetu/middlewares"
	"kalasetu/models"
	"strconv"
)

// CreateEvent is the resolver for the createEvent field.
func (r *mutationResolver) CreateEvent(ctx context.Context, input model.CreateEventInput) (*model.Event, error) {
	userID := optionalUserID(ctx)
	if userID == 0 {
		userID = 1
	}

	event, err := r.eventService.Create(ctx, userID, models.CreateEventInput{
		Name:      input.Name,
		StartDate: input.StartDate,
		Duration:  input.Duration,
		Banner:    toUploadMedia(input.Banner),
	})
	if err != nil {
		return nil, err
	}
	return toGraphEvent(event), nil
}

// UpdateEvent is the resolver for the updateEvent field.
func (r *mutationResolver) UpdateEvent(ctx context.Context, id string, input model.UpdateEventInput) (*model.Event, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	eventID, err := parseEventID(id)
	if err != nil {
		return nil, err
	}

	event, err := r.eventService.Update(ctx, userID, eventID, models.UpdateEventInput{
		Name:      input.Name,
		StartDate: input.StartDate,
		Duration:  input.Duration,
		Banner:    toUploadMedia(input.Banner),
	})
	if err != nil {
		return nil, err
	}
	return toGraphEvent(event), nil
}

// DeleteEvent is the resolver for the deleteEvent field.
func (r *mutationResolver) DeleteEvent(ctx context.Context, id string) (bool, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return false, err
	}
	eventID, err := parseEventID(id)
	if err != nil {
		return false, err
	}

	if err := r.eventService.Delete(ctx, userID, eventID); err != nil {
		return false, err
	}
	return true, nil
}

// OnboardUser is the resolver for the onboardUser field.
func (r *mutationResolver) OnboardUser(ctx context.Context, input model.OnboardingInput) (bool, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return false, err
	}

	var bio string
	if input.Bio != nil {
		bio = *input.Bio
	}

	var profilePicture string
	if input.ProfilePicture != nil {
		profilePicture = *input.ProfilePicture
	}

	onboardingUser := models.OnboardingUser{
		Name:           input.Name,
		Role:           input.Role,
		Location:       input.Location,
		Labels:         input.Labels,
		Bio:            bio,
		ProfilePicture: profilePicture,
	}

	if err := r.userService.StartOnboarding(ctx, userID, onboardingUser); err != nil {
		return false, err
	}

	return true, nil
}

// SubmitApplication is the resolver for the submitApplication field.
func (r *mutationResolver) SubmitApplication(ctx context.Context, input model.CreateApplicationInput) (*model.Application, error) {
	userID := optionalUserID(ctx)
	if userID == 0 {
		userID = 1
	}

	var oppIDPtr *int
	if input.OpportunityID != nil && *input.OpportunityID != "" {
		if val, err := strconv.Atoi(*input.OpportunityID); err == nil {
			oppIDPtr = &val
		}
	}

	eventID, err := strconv.Atoi(input.EventID)
	if err != nil {
		eventID = 1
	}

	serviceInput := models.CreateApplicationInput{
		OpportunityID:  oppIDPtr,
		EventID:        eventID,
		ApplicantName:  derefString(input.ApplicantName),
		ApplicantEmail: derefString(input.ApplicantEmail),
		ApplicantPhone: derefString(input.ApplicantPhone),
		Description:    derefString(input.Description),
		ResumeURL:      derefString(input.ResumeURL),
	}

	application, err := r.applicationService.Create(
		ctx,
		userID,
		serviceInput,
	)

	if err != nil {
		return nil, err
	}

	return toGraphApplication(application), nil
}

// UpdateApplicationStatus is the resolver for the updateApplicationStatus field.
func (r *mutationResolver) UpdateApplicationStatus(ctx context.Context, id string, status string) (bool, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return false, err
	}
	appID, err := strconv.Atoi(id)
	if err != nil {
		return false, fmt.Errorf("invalid application id: %s", id)
	}

	if err := r.applicationService.UpdateStatus(ctx, userID, appID, status); err != nil {
		return false, err
	}
	return true, nil
}

// CreateOpportunity is the resolver for the createOpportunity field.
func (r *mutationResolver) CreateOpportunity(ctx context.Context, input model.CreateOpportunityInput) (*model.Opportunity, error) {
	userID := optionalUserID(ctx)
	if userID == 0 {
		userID = 1
	}

	eventID, err := strconv.Atoi(input.EventID)
	if err != nil {
		eventID = 1
	}

	status := "ACTIVE"
	if input.Status != nil && *input.Status != "" {
		status = *input.Status
	}
	totalPos := 1
	if input.TotalPositions != nil {
		totalPos = int(*input.TotalPositions)
	}

	oppInput := models.CreateOpportunityInput{
		EventID:        eventID,
		Title:          input.Title,
		Description:    derefString(input.Description),
		Categories:     input.Categories,
		Location:       derefString(input.Location),
		StartDate:      derefString(input.StartDate),
		EndDate:        derefString(input.EndDate),
		TotalPositions: totalPos,
		Status:         status,
	}

	opp, err := r.opportunityService.Create(ctx, userID, oppInput)
	if err != nil {
		return nil, err
	}
	return toGraphOpportunity(opp), nil
}

// UpdateOpportunity is the resolver for the updateOpportunity field.
func (r *mutationResolver) UpdateOpportunity(ctx context.Context, id string, input model.UpdateOpportunityInput) (*model.Opportunity, error) {
	userID := optionalUserID(ctx)
	if userID == 0 {
		userID = 1
	}
	oppID, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid opportunity id: %s", id)
	}

	var totalPos *int
	if input.TotalPositions != nil {
		tp := int(*input.TotalPositions)
		totalPos = &tp
	}

	oppInput := models.UpdateOpportunityInput{
		Title:          input.Title,
		Description:    input.Description,
		Categories:     input.Categories,
		Location:       input.Location,
		StartDate:      input.StartDate,
		EndDate:        input.EndDate,
		TotalPositions: totalPos,
		Status:         input.Status,
	}

	opp, err := r.opportunityService.Update(ctx, userID, oppID, oppInput)
	if err != nil {
		return nil, err
	}
	return toGraphOpportunity(opp), nil
}

// CreateListing is the resolver for the createListing field.
func (r *mutationResolver) CreateListing(ctx context.Context, input model.CreateListingInput) (*model.Listing, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	categoryID, err := strconv.Atoi(input.CategoryID)
	if err != nil {
		return nil, fmt.Errorf("invalid category id: %s", input.CategoryID)
	}
	var description string
	if input.Description != nil {
		description = *input.Description
	}

	listing, err := r.listingService.Create(ctx, userID, models.CreateListingInput{
		Title:       input.Title,
		Description: description,
		Price:       input.Price,
		Stock:       int(input.Stock),
		ImageURLs:   input.ImageUrls,
		CategoryID:  categoryID,
	})
	if err != nil {
		return nil, err
	}
	return toGraphListing(listing), nil
}

// UpdateListing is the resolver for the updateListing field.
func (r *mutationResolver) UpdateListing(ctx context.Context, id string, input model.UpdateListingInput) (*model.Listing, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	listingID, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid listing id: %s", id)
	}

	patch := models.UpdateListingInput{
		Title:       input.Title,
		Description: input.Description,
		Price:       input.Price,
		ImageURLs:   input.ImageUrls,
	}
	if input.Stock != nil {
		stock := int(*input.Stock)
		patch.Stock = &stock
	}
	if input.CategoryID != nil {
		categoryID, err := strconv.Atoi(*input.CategoryID)
		if err != nil {
			return nil, fmt.Errorf("invalid category id: %s", *input.CategoryID)
		}
		patch.CategoryID = &categoryID
	}

	listing, err := r.listingService.Update(ctx, userID, listingID, patch)
	if err != nil {
		return nil, err
	}
	return toGraphListing(listing), nil
}

// ArchiveListing is the resolver for the archiveListing field.
func (r *mutationResolver) ArchiveListing(ctx context.Context, id string) (bool, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return false, err
	}
	listingID, err := strconv.Atoi(id)
	if err != nil {
		return false, fmt.Errorf("invalid listing id: %s", id)
	}
	if err := r.listingService.Archive(ctx, userID, listingID); err != nil {
		return false, err
	}
	return true, nil
}

// AddToCart is the resolver for the addToCart field.
func (r *mutationResolver) AddToCart(ctx context.Context, listingID string, quantity *int32) (*model.Cart, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	id, err := strconv.Atoi(listingID)
	if err != nil {
		return nil, fmt.Errorf("invalid listing id: %s", listingID)
	}
	qty := 1
	if quantity != nil {
		qty = int(*quantity)
	}
	cart, err := r.cartService.Add(ctx, userID, id, qty)
	if err != nil {
		return nil, err
	}
	return toGraphCart(cart), nil
}

// UpdateCartItem is the resolver for the updateCartItem field.
func (r *mutationResolver) UpdateCartItem(ctx context.Context, listingID string, quantity int32) (*model.Cart, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	id, err := strconv.Atoi(listingID)
	if err != nil {
		return nil, fmt.Errorf("invalid listing id: %s", listingID)
	}
	cart, err := r.cartService.SetQuantity(ctx, userID, id, int(quantity))
	if err != nil {
		return nil, err
	}
	return toGraphCart(cart), nil
}

// RemoveFromCart is the resolver for the removeFromCart field.
func (r *mutationResolver) RemoveFromCart(ctx context.Context, listingID string) (*model.Cart, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	id, err := strconv.Atoi(listingID)
	if err != nil {
		return nil, fmt.Errorf("invalid listing id: %s", listingID)
	}
	cart, err := r.cartService.Remove(ctx, userID, id)
	if err != nil {
		return nil, err
	}
	return toGraphCart(cart), nil
}

// Checkout is the resolver for the checkout field.
func (r *mutationResolver) Checkout(ctx context.Context, shippingAddress model.ShippingAddressInput) (*model.Order, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	s := shippingAddress
	ship := models.ShippingAddress{
		Name: s.Name, Phone: s.Phone, Line1: s.Line1, City: s.City,
		State: s.State, PostalCode: s.PostalCode, Country: s.Country,
	}
	if s.Line2 != nil {
		ship.Line2 = *s.Line2
	}
	order, err := r.orderService.Checkout(ctx, userID, ship)
	if err != nil {
		return nil, err
	}
	return toGraphOrder(order), nil
}

// CreateCheckoutSession is the resolver for the createCheckoutSession field.
func (r *mutationResolver) CreateCheckoutSession(ctx context.Context, shippingAddress model.ShippingAddressInput) (*model.CheckoutSession, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	s := shippingAddress
	ship := models.ShippingAddress{
		Name: s.Name, Phone: s.Phone, Line1: s.Line1, City: s.City,
		State: s.State, PostalCode: s.PostalCode, Country: s.Country,
	}
	if s.Line2 != nil {
		ship.Line2 = *s.Line2
	}
	session, err := r.checkoutSessionService.Create(ctx, userID, ship)
	if err != nil {
		return nil, err
	}
	return toGraphCheckoutSession(session), nil
}

// UpdateOrderItemStatus is the resolver for the updateOrderItemStatus field.
func (r *mutationResolver) UpdateOrderItemStatus(ctx context.Context, id string, status model.FulfilmentStatus) (*model.SellerOrderItem, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	itemID, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid order item id: %s", id)
	}
	item, err := r.orderService.UpdateItemStatus(ctx, userID, itemID, models.FulfilmentStatus(status))
	if err != nil {
		return nil, err
	}
	return toGraphSellerOrderItem(item), nil
}

// CancelOrderItem is the resolver for the cancelOrderItem field.
func (r *mutationResolver) CancelOrderItem(ctx context.Context, id string) (*model.SellerOrderItem, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	itemID, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid order item id: %s", id)
	}
	item, err := r.orderService.CancelItem(ctx, userID, itemID)
	if err != nil {
		return nil, err
	}
	return toGraphSellerOrderItem(item), nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.Post, error) {
	userID := optionalUserID(ctx)
	if userID == 0 {
		userID = 1
	}

	categoryID, err := parseOptionalID(input.CategoryID)
	if err != nil {
		return nil, err
	}

	post, err := r.postService.Create(ctx, userID, models.CreatePostInput{
		Content:    input.Content,
		Media:      toUploadMediaList(input.Media),
		CategoryID: categoryID,
	})
	if err != nil {
		return nil, err
	}
	return toGraphPost(post), nil
}

// UpdatePost is the resolver for the updatePost field.
func (r *mutationResolver) UpdatePost(ctx context.Context, id string, input model.UpdatePostInput) (*model.Post, error) {
	userID := optionalUserID(ctx)
	if userID == 0 {
		userID = 1
	}
	postID, err := parsePostID(id)
	if err != nil {
		return nil, err
	}
	categoryID, err := parseOptionalID(input.CategoryID)
	if err != nil {
		return nil, err
	}

	post, err := r.postService.Update(ctx, userID, postID, models.UpdatePostInput{
		Content:    input.Content,
		CategoryID: categoryID,
	})
	if err != nil {
		return nil, err
	}
	return toGraphPost(post), nil
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, id string) (bool, error) {
	userID := optionalUserID(ctx)
	if userID == 0 {
		userID = 1
	}
	postID, err := parsePostID(id)
	if err != nil {
		return false, err
	}

	if err := r.postService.Delete(ctx, userID, postID); err != nil {
		return false, err
	}
	return true, nil
}

// LikePost is the resolver for the likePost field.
func (r *mutationResolver) LikePost(ctx context.Context, id string) (bool, error) {
	userID := optionalUserID(ctx)
	if userID == 0 {
		userID = 1
	}
	postID, err := parsePostID(id)
	if err != nil {
		return false, err
	}
	if _, err := r.postService.GetByID(ctx, postID, userID); err != nil {
		return false, err
	}
	if err := r.likeService.Like(ctx, userID, postID); err != nil {
		return false, err
	}
	return true, nil
}

// UnLikePost is the resolver for the unLikePost field.
func (r *mutationResolver) UnLikePost(ctx context.Context, id string) (bool, error) {
	userID := optionalUserID(ctx)
	if userID == 0 {
		userID = 1
	}
	postID, err := parsePostID(id)
	if err != nil {
		return false, err
	}
	if _, err := r.postService.GetByID(ctx, postID, userID); err != nil {
		return false, err
	}
	if err := r.likeService.Unlike(ctx, userID, postID); err != nil {
		return false, err
	}
	return true, nil
}

// AddComment is the resolver for the addComment field.
func (r *mutationResolver) AddComment(ctx context.Context, input model.CreateCommentInput) (*model.Comment, error) {
	userID := optionalUserID(ctx)
	if userID == 0 {
		userID = 1
	}
	postID, err := parsePostID(input.PostID)
	if err != nil {
		return nil, err
	}
	if _, err := r.postService.GetByID(ctx, postID, userID); err != nil {
		return nil, err
	}

	comment, err := r.commentService.Create(ctx, userID, models.CreateCommentInput{
		PostID:  postID,
		Content: input.Content,
	})
	if err != nil {
		return nil, err
	}
	return toGraphComment(comment), nil
}

// UpdateComment is the resolver for the updateComment field.
func (r *mutationResolver) UpdateComment(ctx context.Context, id string, input model.UpdateCommentInput) (*model.Comment, error) {
	userID := optionalUserID(ctx)
	if userID == 0 {
		userID = 1
	}
	commentID, err := parseCommentID(id)
	if err != nil {
		return nil, err
	}

	comment, err := r.commentService.Update(ctx, userID, commentID, input.Content)
	if err != nil {
		return nil, err
	}
	return toGraphComment(comment), nil
}

// DeleteComment is the resolver for the deleteComment field.
func (r *mutationResolver) DeleteComment(ctx context.Context, id string) (bool, error) {
	userID := optionalUserID(ctx)
	if userID == 0 {
		userID = 1
	}
	commentID, err := parseCommentID(id)
	if err != nil {
		return false, err
	}

	if err := r.commentService.Delete(ctx, userID, commentID); err != nil {
		return false, err
	}
	return true, nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "OK", nil
}

// Events is the resolver for the events field.
func (r *queryResolver) Events(ctx context.Context) ([]*model.Event, error) {
	events, err := r.eventService.List(ctx)
	if err != nil {
		return nil, err
	}
	return toGraphEvents(events), nil
}

// Event is the resolver for the event field.
func (r *queryResolver) Event(ctx context.Context, id string) (*model.Event, error) {
	eventID, err := parseEventID(id)
	if err != nil {
		return nil, err
	}

	event, err := r.eventService.GetByID(ctx, eventID)
	if err != nil {
		return nil, err
	}
	return toGraphEvent(event), nil
}

// UserEvents is the resolver for the userEvents field.
func (r *queryResolver) UserEvents(ctx context.Context) ([]*model.Event, error) {
	userID, err := middlewares.GetUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	events, err := r.eventService.ListByUser(ctx, userID)
	if err != nil {
		return nil, err
	}

	return toGraphEvents(events), nil
}

// Application is the resolver for the application field.
func (r *queryResolver) Application(ctx context.Context, id string) (*model.Application, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	appID, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid application id: %s", id)
	}

	app, err := r.applicationService.FindByID(ctx, userID, appID)
	if err != nil {
		return nil, err
	}
	return toGraphApplication(app), nil
}

// MyApplications is the resolver for the myApplications field.
func (r *queryResolver) MyApplications(ctx context.Context) ([]*model.Application, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	apps, err := r.applicationService.ListByApplier(ctx, userID)
	if err != nil {
		return nil, err
	}
	return toGraphApplications(apps), nil
}

// ApplicationsByOpportunity is the resolver for the applicationsByOpportunity field.
func (r *queryResolver) ApplicationsByOpportunity(ctx context.Context, opportunityID string) ([]*model.Application, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	oppID, err := strconv.Atoi(opportunityID)
	if err != nil {
		return nil, fmt.Errorf("invalid opportunity id: %s", opportunityID)
	}

	apps, err := r.applicationService.ListByOpportunity(ctx, userID, oppID)
	if err != nil {
		return nil, err
	}
	return toGraphApplications(apps), nil
}

// ApplicationsByEvent is the resolver for the applicationsByEvent field.
func (r *queryResolver) ApplicationsByEvent(ctx context.Context, eventID string) ([]*model.Application, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	eID, err := strconv.Atoi(eventID)
	if err != nil {
		return nil, fmt.Errorf("invalid event id: %s", eventID)
	}
	apps, err := r.applicationService.ListByEvent(ctx, userID, eID)
	if err != nil {
		return nil, err
	}
	return toGraphApplications(apps), nil
}

// OpportunitiesByEvent is the resolver for the opportunitiesByEvent field.
func (r *queryResolver) OpportunitiesByEvent(ctx context.Context, eventID string) ([]*model.Opportunity, error) {
	eID, err := strconv.Atoi(eventID)
	if err != nil {
		return nil, fmt.Errorf("invalid event id: %s", eventID)
	}
	opps, err := r.opportunityService.ListByEvent(ctx, eID)
	if err != nil {
		return nil, err
	}
	return toGraphOpportunities(opps), nil
}

// Opportunity is the resolver for the opportunity field.
func (r *queryResolver) Opportunity(ctx context.Context, id string) (*model.Opportunity, error) {
	oppID, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid opportunity id: %s", id)
	}
	opp, err := r.opportunityService.FindByID(ctx, oppID)
	if err != nil {
		return nil, err
	}
	return toGraphOpportunity(opp), nil
}

// Profile is the resolver for the profile field.
func (r *queryResolver) Profile(ctx context.Context, userID string) (*model.Profile, error) {
	parsedID, err := parseProfileID(userID)
	if err != nil {
		return nil, err
	}

	profile, err := r.profileService.GetProfile(ctx, parsedID)
	if err != nil {
		return nil, err
	}
	return toGraphProfile(profile), nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*model.Category, error) {
	categories, err := r.listingService.ListCategories(ctx)
	if err != nil {
		return nil, err
	}
	return toGraphCategories(categories), nil
}

// Listing is the resolver for the listing field.
func (r *queryResolver) Listing(ctx context.Context, id string) (*model.Listing, error) {
	listingID, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid listing id: %s", id)
	}
	viewerID, _ := middlewares.GetUserIDFromContext(ctx) // 0 when anonymous
	listing, err := r.listingService.GetByID(ctx, viewerID, listingID)
	if err != nil {
		return nil, err
	}
	return toGraphListing(listing), nil
}

// MyListings is the resolver for the myListings field.
func (r *queryResolver) MyListings(ctx context.Context) ([]*model.Listing, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	listings, err := r.listingService.MyListings(ctx, userID)
	if err != nil {
		return nil, err
	}
	return toGraphListings(listings), nil
}

// Listings is the resolver for the listings field.
func (r *queryResolver) Listings(ctx context.Context, filter *model.ListingFilter, sort *model.ListingSort, limit *int32, offset *int32) ([]*model.Listing, error) {
	q := models.ListingQuery{Sort: models.SortNewest, Limit: 20}
	if filter != nil {
		if filter.Query != nil {
			q.Query = *filter.Query
		}
		if filter.CategoryID != nil {
			id, err := strconv.Atoi(*filter.CategoryID)
			if err != nil {
				return nil, fmt.Errorf("invalid category id: %s", *filter.CategoryID)
			}
			q.CategoryID = &id
		}
		q.MinPrice = filter.MinPrice
		q.MaxPrice = filter.MaxPrice
		q.InStockOnly = filter.InStockOnly != nil && *filter.InStockOnly
	}
	if sort != nil {
		q.Sort = models.ListingSort(*sort)
	}
	if limit != nil {
		q.Limit = int(*limit)
	}
	if offset != nil {
		q.Offset = int(*offset)
	}

	listings, err := r.listingService.Browse(ctx, q)
	if err != nil {
		return nil, err
	}
	return toGraphListings(listings), nil
}

// FeaturedListings is the resolver for the featuredListings field.
func (r *queryResolver) FeaturedListings(ctx context.Context, limit *int32) ([]*model.Listing, error) {
	n := 8
	if limit != nil {
		n = int(*limit)
	}
	listings, err := r.listingService.Featured(ctx, n)
	if err != nil {
		return nil, err
	}
	return toGraphListings(listings), nil
}

// MyCart is the resolver for the myCart field.
func (r *queryResolver) MyCart(ctx context.Context) (*model.Cart, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	cart, err := r.cartService.Get(ctx, userID)
	if err != nil {
		return nil, err
	}
	return toGraphCart(cart), nil
}

// MyOrders is the resolver for the myOrders field.
func (r *queryResolver) MyOrders(ctx context.Context) ([]*model.Order, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	orders, err := r.orderService.MyOrders(ctx, userID)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Order, 0, len(orders))
	for i := range orders {
		result = append(result, toGraphOrder(&orders[i]))
	}
	return result, nil
}

// SellerOrderItems is the resolver for the sellerOrderItems field.
func (r *queryResolver) SellerOrderItems(ctx context.Context, status *model.FulfilmentStatus) ([]*model.SellerOrderItem, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	var filter *models.FulfilmentStatus
	if status != nil {
		st := models.FulfilmentStatus(*status)
		filter = &st
	}
	items, err := r.orderService.SellerOrderItems(ctx, userID, filter)
	if err != nil {
		return nil, err
	}
	result := make([]*model.SellerOrderItem, 0, len(items))
	for i := range items {
		result = append(result, toGraphSellerOrderItem(&items[i]))
	}
	return result, nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, limit *int32, offset *int32) ([]*model.Post, error) {
	currUserID := optionalUserID(ctx)
	posts, err := r.postService.List(ctx, currUserID, int32PtrToIntPtr(limit), int32PtrToIntPtr(offset))
	if err != nil {
		return nil, err
	}
	return toGraphPosts(posts), nil
}

// PostsByUser is the resolver for the postsByUser field.
func (r *queryResolver) PostsByUser(ctx context.Context, userID string, limit *int32, offset *int32) ([]*model.Post, error) {
	targetUserID, err := strconv.Atoi(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %s", userID)
	}
	currUserID := optionalUserID(ctx)
	posts, err := r.postService.ListByUser(ctx, targetUserID, currUserID, int32PtrToIntPtr(limit), int32PtrToIntPtr(offset))
	if err != nil {
		return nil, err
	}
	return toGraphPosts(posts), nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	postID, err := parsePostID(id)
	if err != nil {
		return nil, err
	}

	currUserID := optionalUserID(ctx)
	post, err := r.postService.GetByID(ctx, postID, currUserID)
	if err != nil {
		return nil, err
	}
	return toGraphPost(post), nil
}

// LikesOfPost is the resolver for the likesOfPost field.
func (r *queryResolver) LikesOfPost(ctx context.Context, id string) ([]*model.Author, error) {
	postID, err := parsePostID(id)
	if err != nil {
		return nil, err
	}
	currUserID := optionalUserID(ctx)
	if _, err := r.postService.GetByID(ctx, postID, currUserID); err != nil {
		return nil, err
	}

	authors, err := r.likeService.ListByPost(ctx, postID)
	if err != nil {
		return nil, err
	}
	return toGraphAuthors(authors), nil
}

// CommentsOfPost is the resolver for the commentsOfPost field.
func (r *queryResolver) CommentsOfPost(ctx context.Context, id string) ([]*model.Comment, error) {
	postID, err := parsePostID(id)
	if err != nil {
		return nil, err
	}
	comments, err := r.commentService.ListByPost(ctx, postID)
	if err != nil {
		return nil, err
	}
	return toGraphComments(comments), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
